# Generated by Django 2.2 on 2019-07-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policestation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policestation',
            name='slug',
            field=models.SlugField(default=False, unique=True),
        ),
    ]
