# Generated by Django 2.2 on 2019-05-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminsite', '0002_logindetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostperson',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lostperson',
            name='image',
            field=models.ImageField(upload_to='picture/'),
        ),
        migrations.AlterField(
            model_name='wanted',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wanted',
            name='image',
            field=models.ImageField(height_field=50, max_length=50, upload_to='picture/', width_field=50),
        ),
    ]
