# Generated by Django 2.2 on 2019-06-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminsite', '0003_auto_20190505_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanted',
            name='image',
            field=models.ImageField(upload_to='picture/'),
        ),
    ]
