# Generated by Django 2.2 on 2019-04-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('idno', models.IntegerField()),
                ('image', models.ImageField(upload_to=None)),
                ('Time', models.TimeField()),
                ('Date', models.DateField()),
            ],
        ),
    ]
