# Generated by Django 2.2 on 2019-04-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostPerson',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Wanted',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
