# Generated by Django 2.2 on 2019-04-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20190404_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='idno',
        ),
        migrations.RemoveField(
            model_name='report',
            name='name',
        ),
    ]
